import { Zen_Maru_Gothic } from "next/font/google";
import { Inter } from "next/font/google";
import Stars from "../components/stars";
import StyledComponentsRegistry from "./lib/registry";

const Zen = Zen_Maru_Gothic({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Guia Quântico",
  description: "Generated by Next.js",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Zen.className} ${inter.variable}`}>
        <StyledComponentsRegistry>
          <Stars />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
