import { Zen_Maru_Gothic } from "next/font/google";
import Stars from "../components/stars";

const Zen = Zen_Maru_Gothic({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Guia Quântico",
  description: "Generated by Next.js",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Zen.className}>
        <Stars />
        {children}
      </body>
    </html>
  );
}
